from bindflow.free_energy import gather_results
from bindflow import root_path as abfe_root_path

out_approach_path = config["out_approach_path"]

# System Generation
include: 'build_ligand_systems.smk'

# Do Equilibration
include: abfe_root_path + '/rules/equi/Snakefile'

if config["calculation_type"] == "fep":
    # Do FEP
    include: abfe_root_path + '/rules/fep/Snakefile'
elif config["calculation_type"] == "mmpbsa":
    # Do MMPBSA
    include: abfe_root_path + '/rules/mmpbsa/Snakefile'