name: abfe
channels:
  - conda-forge
dependencies:
  - python >=3.8, <3.10 # biosimspace use this python definition
  - pip
  - parmed
  - pdbfixer
  - openmm
  - openmmforcefields
  - openff-toolkit
  - michellab/label/dev::biosimspace
  - bioconda::snakemake
  - espaloma >=0.3.1
  - dgl::dglteam <1
  # - nvidia::cuda-toolkit=11.4.2
  # - pip:
  #   - git+https://github.com/ale94mleon/BindFlow.git
