name: abfe
channels:
  - conda-forge
dependencies:
  - python >=3.8, <3.10 # biosimspace use this python definition
  - pip
  - conda-build
  - gromacs=2022.2
  - parmed
  - pdbfixer
  - openmm
  - openff-toolkit
  - openbiosim::biosimspace
  - bioconda::snakemake
  # - nvidia::cuda-toolkit=11.4.2