name: BindFlow
channels:
  - conda-forge
dependencies:
  - python >=3.8,<3.11
  - pip
  - bioconda::snakemake
  - ambertools =22.5
  - mpi4py <=3.1.5
  - openmm =8.1.1
  - openmmforcefields =0.11.2
  - pdbfixer
  - openff-toolkit =0.14.5
  - parmed
  - espaloma =0.3.1
  - dglteam::dgl
  - scipy >=1.7.3
  - graphviz
  # - nvidia::cuda-toolkit=11.4.2
  # - pip:
  #   - git+https://github.com/ale94mleon/BindFlow.git

