name: BindFlow
channels:
  - conda-forge
dependencies:
  - python >=3.8,<3.11
  - pip
  - bioconda::snakemake
  - ambertools ==22.0
  - openmm ==8.0
  - openmmforcefields
  - pdbfixer
  - openff-toolkit <=0.14.3
  - espaloma =0.3.1
  - dglteam::dgl

