from abfe.free_energy import gather_results
from abfe import root_path as abfe_root_path

# Gather Results

#Final Check Job
rule gather_receptor_results:
    input:
        prior_result_paths=expand(config["out_approach_path"] + "/{ligand_names}/{replica}/dG_results.csv",ligand_names=config['ligand_names'],replica=list(map(str, range(1,1 + config['replicas']))))
    output:
        out_dg_file=config["out_approach_path"]+"/abfe_results.csv",
    run:
        gather_results.get_all_dgs(
            root_folder_path = input.approach_path,
            out_csv=os.path.join(output.out_dg_file)
        )

# Do Equilibration
include: abfe_root_path + '/rules/equi/Snakefile'

# Do FEP
include: abfe_root_path + '/rules/fep/Snakefile'

# System Generation
include: 'build_ligand_systems.smk'