cluster:
  type: FrontEnd
  options:
    calculation: None   
extra_directives: # Optional
  dependencies:
    - 'export GMX_MAXBACKUP=-1'
  mdrun:
    all:
      cpi: False
      stepout: 5000
      v: True
mdp: # optional
  complex:
    equi:
      00_min:
        nsteps: 100000
      01_nvt:
          dt: 0.002
          nsteps: 37500
      02_nvt:
          dt: 0.003
          nsteps: 17500
      03_npt:
        dt: 0.003
        nsteps: 25000
      04_npt:
        dt: 0.004
        nsteps: 25000
      prod:
        dt: 0.004
        nsteps: 25000
        nstxout-compressed: 1250
    mmpbsa:
      prod:
        dt: 0.004
        nsteps: 100000
        nstxout-compressed: 2500
mmpbsa:
  general: 
    c2_entropy: 1
#    qh_entropy: 1
    interaction_entropy: 1
  pb: {}
  gb: {}