name: BindFlow-dev
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - pip
  - bioconda::snakemake
  - ambertools
  - openmm
  - openmmforcefields
  - pdbfixer
  - openff-toolkit
  - espaloma>=0.3.2
  - pyyaml
  - parmed
  - pandas
  - numpy
  - mpi4py=3.1.5
  - alchemlyb
  - mdanalysis
  - pymbar
  - uncertainties
  - pip:
      - mdrestraintsgenerator>=0.2.1
      - rdkit
      - toff>=0.2.0


