#Final Check Job
run_path = config["run_path"]

if config["complex_type"] == 'soluble':

    #Setup: Build dir structure of equil
    include: 'ligand/setup.smk'
    include: 'complex/soluble/setup.smk'
        
    #RUN: Equil
    include: 'ligand/simulation.smk'
    include: 'complex/soluble/simulation.smk'

elif config["complex_type"] == 'membrane':

    #Setup: Build dir structure of equil
    include: 'ligand/setup.smk'
    include: 'complex/membrane/setup.smk'
        
    #RUN: Equil
    include: 'ligand/simulation.smk'
    include: 'complex/membrane/simulation.smk'  

else:
    rule equi_not_implemented:
        output:
            run_path+"/equi_not_implemented.txt"
        shell:
            "echo 'equi simulations, you must give complex_type = soluble or membrane' > {output}"

rule equil_results:
    input:
        gro_complex=run_path+"/complex/equil-mdsim/boreschcalc/ClosestRestraintFrame.gro",
        top_complex=run_path+"/complex/equil-mdsim/boreschcalc/BoreschRestraint.top",
        dG_off_complex=run_path+"/complex/equil-mdsim/boreschcalc/dG_off.dat",
        gro_ligand=run_path+"/ligand/equil-mdsim/npt_equil2/npt_equil2.gro",
        cpt_ligand=run_path+"/ligand/equil-mdsim/npt_equil2/npt_equil2.cpt"

