mdp:  # optional
  ligand:
    equi:
      <step1>:
        <mdp_ligand_equi_step1_options>
      <step2>:
        <mdp_ligand_equi_step2_options>
    fep:
      vdw:
        <step1>:
          <mdp_ligand_fep_vdw_step1_options>
        <step2>:
          <mdp_ligand_fep_vdw_step2_options>
      coul:
        <step1>:
          <mdp_ligand_fep_coul_step1_options>
        <step2>:
          <mdp_ligand_fep_coul_step2_options>
  complex:
    equi:
      <step1>:
        <mdp_complex_equi_step1_options>
      <step2>:
        <mdp_complex_equi_step2_options>
    fep:
      vdw:
        <step1>:
          <mdp_complex_fep_vdw_step1_options>
        <step2>:
          <mdp_complex_fep_vdw_step2_options>
      coul:
        <step1>:
          <mdp_complex_fep_coul_step1_options>
        <step2>:
          <mdp_complex_fep_coul_step2_options>
      bonded:
        <step1>:
          <mdp_complex_fep_bonded_step1_options>
        <step2>:
          <mdp_complex_fep_bonded_step2_options>