cluster:
  options:
    calculation: None   
extra_directives: # Optional
  dependencies:
    - 'export GMX_MAXBACKUP=-1'
  mdrun:
    all:
      cpi: False
      stepout: 5000
      v: True
mdp: # optional
  complex:
    equi:
      00_min:
        nsteps: 100000
      01_nvt:
          dt: 0.002
          nsteps: 5000
      02_nvt:
          dt: 0.003
          nsteps: 5000
      03_npt:
        dt: 0.003
        nsteps: 7500
      04_npt:
        dt: 0.004
        nsteps: 15000
      prod:
        dt: 0.004
        nsteps: 237500
        nstxout-compressed: 11875
    mmpbsa:
      prod:
        dt: 0.004
        nsteps: 37500
        nstxout-compressed: 1250
mmpbsa:
  general: 
    c2_entropy: 1
    #qh_entropy: 1
    interaction_entropy: 1
    startframe: 10 # recommended burn phase to skip frames directly after the split
  pb: {} # enable MMPBSA computation
  gb: {} # enable MMGBSA computation