# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.8, 3.9]
        exclude:
          - os: macOS-latest
            python-version: '3.10'
    steps:
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge,defaults,bioconda
        channel-priority: true
        activate-environment: anaconda-client-env
        environment-file: environment.yml
    - name: Install pip dependencies and bindflow on test mode
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        pip install -e .[test]
        python -m pip install pytest-cov
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/bindflow --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 src/bindflow --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        echo after "Lint with flake8" My python version is actually: $(python --version).
    - name: Test with pytest
      run: |
        pytest --cov src/bindflow
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3